# Generated by Django 4.2.12 on 2024-08-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.SlugField(blank=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
