# Generated by Django 4.2.12 on 2024-08-13 20:00

from django.db import migrations, models
import paste.models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='cdate',
            field=models.DateTimeField(default=paste.models.nowdjangotz, verbose_name='creation date'),
        ),
        migrations.AddField(
            model_name='paste',
            name='mdate',
            field=models.DateTimeField(default=paste.models.nowdjangotz, verbose_name='modification date'),
        ),
    ]
