# Generated by Django 4.2.12 on 2024-08-16 05:07
# Manually altered.

from django.db import migrations, models
import paste.models

def setdeftoken(apps, schema):
	ps = apps.get_model('paste', 'Paste')
	for p in ps.objects.all().iterator():
		p.token = paste.models.mkrandstr32()
		p.save()

# Nothing particular to be done here
def reverse_setdeftoken():
	pass

class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0002_paste_cdate_paste_mdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='token',
            field=models.CharField(default=paste.models.mkrandstr32, max_length=32, verbose_name='ownership token'),
        ),
        migrations.RunPython(setdeftoken, reverse_setdeftoken),
    ]
